In [11]:
import numpy as np

A = np.array([2 ,-4 ,-4 ,-2 , 1 , 3 ,-4 ,-3 , 1 ,-5,
                -3 , 6 ,-3 , 0 , 0 , 3 , 4 ,-1 , 1 ,-1,
                -4 ,-5 , 1 ,-3 , 1 ,-3 ,-5 ,-5 , 0 ,-4,
                 5 ,-3 , 0 , 5 ,-4 , 3 ,-5 ,-4 ,-5 ,-2,
                 5 , 3 ,-1 , 4 , 3 , 5 , 4 , 2 ,-1 , 3,
                 4 , 3 ,-1 , 1 , 2 ,-5 , 3 , 1 ,-5 , 1,
                 4 , 5 ,-1 , 1 ,-5 ,-2 , 4 , 2 ,-4 ,-2,
                -4 ,-1 , 3 ,-3 ,-3 , 5 , 2 , 5 ,-1 ,-5,
                 5 , 5 , 2 ,-4 , 2 ,-3 ,-3 , 2 , 5 ,-2,
                -4 , 4 , 2 ,-4 , 5 ,-2 ,-4 ,-4 ,-4 ,-5])
A = np.reshape(A,(-1,10))
print(A)
print(np.linalg.det(A))
inverse = np.linalg.inv(A)
inverse

[[ 2 -4 -4 -2  1  3 -4 -3  1 -5]
 [-3  6 -3  0  0  3  4 -1  1 -1]
 [-4 -5  1 -3  1 -3 -5 -5  0 -4]
 [ 5 -3  0  5 -4  3 -5 -4 -5 -2]
 [ 5  3 -1  4  3  5  4  2 -1  3]
 [ 4  3 -1  1  2 -5  3  1 -5  1]
 [ 4  5 -1  1 -5 -2  4  2 -4 -2]
 [-4 -1  3 -3 -3  5  2  5 -1 -5]
 [ 5  5  2 -4  2 -3 -3  2  5 -2]
 [-4  4  2 -4  5 -2 -4 -4 -4 -5]]
-71937460.99999973


array([[ 0.08167226, -0.31055924,  0.06121259, -0.19628694,  0.25388673,
        -0.35804212,  0.38758115, -0.16073999, -0.077822  ,  0.12754424],
       [-0.02945622,  0.08925831, -0.1054214 ,  0.05628385, -0.07796724,
         0.02826112, -0.04946267, -0.00370671,  0.04644929,  0.03721209],
       [-0.11353279, -0.21007024,  0.23475908, -0.11782512,  0.28966423,
        -0.30723607,  0.27989277, -0.05951216, -0.02316299,  0.08404121],
       [-0.28174734,  0.93299979,  0.15567828,  0.69180247, -0.44415098,
         1.15501213, -1.07018042,  0.48344167,  0.41719606, -0.56385232],
       [-0.04365126,  0.22903071,  0.07077272,  0.1386345 , -0.04321114,
         0.36408366, -0.34216975,  0.14120269,  0.11679356, -0.11838903],
       [ 0.09722056, -0.29120481, -0.08223186, -0.19221275,  0.20435962,
        -0.43920432,  0.33053235, -0.13786088, -0.15121479,  0.20459976],
       [-0.01008522, -0.16895028,  0.28644008, -0.22374585,  0.33042067,
        -0.27752796,  0.36928238, -0.09282382