---
# Übungszettel 1, Python Aufgabe
---

**ausgegeben am Mi 22.4.2020 12 Uhr, abzugeben bis Mi 29.4.2020 12 Uhr**

Bearbeitet von: Max Mustermann

Zusammenarbeit mit: -

Übungsgruppe: Otto Normalverbraucher

---

In der Elektrostatik und -Dynamik sind Vektoren und manchmal auch Matrizen unverzichtbar. Anstelle alle Operationen mit Vektoren manuell zu programmieren oder per Hand durchzuführen, kann man diese auch schnell und zuverlässig mit einer Bücherrei durchführen. Wir wollen daher diese Übungsaufgabe nutzen um die Nutzung von `numpy` zu wiederholen.

Benutzen Sie `numpy` um Skalarprodukte (inneres Produkt), Kreuzprodukte und Matrixprodukte mit Python zu berechnen.
* Importieren Sie `numpy` als `np`.
* Definieren Sie die Vektoren $a=[1, 3, 0]$, $b=[-1,0,1]$ und die Matrix $M=[[1,0,1],[0,2,0],[-1,0,1]]$ als numpy array (also z.B. `a=np.array([1,3,0])`)
* Berechnen Sie das Skalarprodukt (`np.dot()` alternativ mit dem Symbol `@` als Malzeichen) $a \circ b$, Kreuzprodukt (`np.cross()`) $a \times b$ und das Matrix-Vektor Produkt (wieder mit dem Skalarprodukt Zeichen) $M \cdot a$
* Zeigen Sie die Ergebnisse der Operationen und die Transponierte der Matrix $M$ (mit `.T` nach dem Namen wird transponiert) mit `print()`.



---
**Erste Hilfe Python:**
* Online-Sprechstunde jeden Mittwoch im Semester von 15-17 Uhr über BigBlueButton
* Studiengruppe im StudIP mit dem Titel “Erste Hilfe Python der SUB Göttingen”
* Übersichts-Pad ( https://pad.gwdg.de/ErsteHilfePython ) als alternative Anlaufstelle

In [6]:
import numpy as np
a = np.array([1,3,0])
b = np.array([-1,0,1])
M = np.array([[1,0,1], [0,2,0], [-1,0,1]])
print(np.dot(a,b))
print(np.cross(a,b))
print(np.dot(M,a))
print(M.T)

-1
[ 3 -1  3]
[ 1  6 -1]
[[ 1  0 -1]
 [ 0  2  0]
 [ 1  0  1]]
