In [2]:
import numpy as np
##ue2
e0 = np.array([2, 1, -1])
el = np.array([1, -1, -1])
em = np.array([-3, 1, 4])

g0 = np.array([3, 0, 1])
gk = np.array([4, -1, 2])

A = np.array([el, em, -gk]).T
rhs = g0 - e0

l, m, k = np.linalg.solve(A, rhs)
print((l, m, k))

print(e0 + l*el + m*em)
print(g0 + k*gk)

(1.2000000000000002, 0.6000000000000001, -0.4)
[1.4 0.4 0.2]
[1.4 0.4 0.2]


In [19]:
##ue3
def hilberto(n):
    j = np.arange(n)
    i = j[:, None]
    return 1 / (i + j + 1)

H = hilberto(4)

print(H)

print(np.linalg.cond(H))

[[1.         0.5        0.33333333 0.25      ]
 [0.5        0.33333333 0.25       0.2       ]
 [0.33333333 0.25       0.2        0.16666667]
 [0.25       0.2        0.16666667 0.14285714]]
15513.738738928929


In [21]:
##ue4
x1 = np.array([0, 1, 0, 1])
x2 = np.array([1, 2, 3, 4])
x3 = np.array([1, 0, 1, 0])
x4 = np.array([0, 0, 1, 1])

A = np.array([x1, x2, x3, x4])

from scipy.linalg import det

# 1. Option: Determinante ist 0
print(det(A))

2.220446049250313e-16
