In [7]:
import numpy as np
import numpy.linalg as npl
import scipy.linalg as spl

v = 0

In [17]:
a = np.arange(5)
mat = np.diag((np.ones(5)))
a @ mat

array([0., 1., 2., 3., 4.])

In [20]:
a = np.arange(24).reshape((2,3,4))
b = np.arange(40).reshape((2,4,5))
print(a @ b)
(a @ b).shape

[[[  70   76   82   88   94]
  [ 190  212  234  256  278]
  [ 310  348  386  424  462]]

 [[1510 1564 1618 1672 1726]
  [1950 2020 2090 2160 2230]
  [2390 2476 2562 2648 2734]]]


(2, 3, 5)

In [34]:
A = np.arange(9).reshape((3, 3))
npl.det(A)
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
b, W = npl.eig(A)
print(b)
print(W)

[ 1.33484692e+01 -1.34846923e+00 -2.48477279e-16]
[[ 0.16476382  0.79969966  0.40824829]
 [ 0.50577448  0.10420579 -0.81649658]
 [ 0.84678513 -0.59128809  0.40824829]]


In [36]:
A = np.diag(np.ones(3)) - np.diag(np.ones(2), 1)
print(f'A = \n {A}')

iA = spl.inv(A)
print(f'A^(-1) = \n {iA}')
print(f'A^(-1) * A = \n {iA @ A}')
print(f'A * A^(-1) = \n {A @ iA}')

A = 
 [[ 1. -1.  0.]
 [ 0.  1. -1.]
 [ 0.  0.  1.]]
A^(-1) = 
 [[1. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
A^(-1) * A = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
A * A^(-1) = 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [37]:
A = np.diag(np.ones(10)) - np.diag(np.ones(9), 1)
x = np.ones(10)

y = A @ x

# Lösen; sollte `== x` sein
spl.solve(A, y)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
H = spl.hilbert(20)
npl.cond(H)

1.4957014723432323e+18

In [39]:
x = np.ones(20)
# erzeuge rechte Seite
y = H @ x

# Addiere kleinen Fehler auf die rechte Seite
y_approx = y.copy()
y_approx[0] = y_approx[0] + 1e-5
print(f'error in y = {npl.norm(y_approx - y) / npl.norm(y)}')

# Gleichungssystem lösen, um eine Lösung x zu erhalten
x_approx = spl.solve(H, y_approx)
print(x_approx)
print(f'error in x = {npl.norm(x_approx - x) / npl.norm(x)}')

error in y = 1.4502495531331887e-06
[ 1.00161940e+00  8.69923607e-01  4.40401617e+00 -4.17948892e+01
  3.04548730e+02 -1.30790421e+03  3.48796151e+03 -5.33187283e+03
  2.74709993e+03  5.25123570e+03 -9.45324535e+03 -6.15672929e+02
  1.52821321e+04 -9.43653740e+03 -1.78178268e+04  3.38874900e+04
 -2.18189283e+04  3.22762743e+03  2.58973788e+03 -9.40326233e+02]
error in x = 11067.447054265858


<ipython-input-39-3a108213ad50>:11: LinAlgWarning: Ill-conditioned matrix (rcond=1.48818e-19): result may not be accurate.
  x_approx = spl.solve(H, y_approx)


In [42]:
x = 1e-15
((x+1) - 1) / x


1.1102230246251565

In [43]:
P, L, U = spl.lu(spl.hilbert(3))
U

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.        ,  0.08333333,  0.08888889],
       [ 0.        ,  0.        , -0.00555556]])