In [4]:
import numpy as np
##ue1
def meanvec(a):
    dim = len(a)
    summ = a.sum()
    return summ/dim

arr = np.array([1,1,1])
meanvec(arr)

1.0

In [21]:
##ue2
np.diag(2*np.ones((100,)), 0) + np.diag(-np.ones((99,)), -1) + np.diag(-np.ones((99,)), 1)

array([[ 2., -1.,  0., ...,  0.,  0.,  0.],
       [-1.,  2., -1., ...,  0.,  0.,  0.],
       [ 0., -1.,  2., ...,  0.,  0.,  0.],
       ...,
       [ 0.,  0.,  0., ...,  2., -1.,  0.],
       [ 0.,  0.,  0., ..., -1.,  2., -1.],
       [ 0.,  0.,  0., ...,  0., -1.,  2.]])

In [8]:
##ue3
from scipy.linalg import hilbert
hil = hilbert(50)
thirdcol = hil[2,:]
print(sum(thirdcol))

3.038043950697448


In [37]:
##ue4
from numpy.random import randint
import numpy as np

mat = np.array([])

for i in range(2*3*4*5):
    a = randint(0,9)
    mat = np.append(a,mat)
    
mat = mat.reshape(2,3,4,5)
print(mat)
mat.sum((2,3))

[[[[6. 7. 6. 2. 7.]
   [1. 1. 7. 4. 8.]
   [6. 7. 3. 0. 0.]
   [1. 3. 2. 5. 6.]]

  [[1. 5. 0. 7. 4.]
   [7. 1. 3. 1. 2.]
   [1. 3. 1. 0. 5.]
   [0. 4. 4. 3. 5.]]

  [[5. 2. 1. 5. 5.]
   [7. 1. 3. 8. 5.]
   [6. 6. 8. 2. 7.]
   [0. 1. 4. 6. 3.]]]


 [[[5. 2. 4. 0. 0.]
   [7. 8. 8. 8. 0.]
   [4. 0. 7. 0. 1.]
   [7. 2. 1. 4. 0.]]

  [[3. 8. 7. 3. 0.]
   [1. 4. 8. 4. 8.]
   [4. 3. 1. 1. 8.]
   [1. 8. 3. 8. 1.]]

  [[6. 3. 1. 2. 6.]
   [1. 6. 2. 4. 5.]
   [8. 4. 4. 7. 8.]
   [7. 5. 0. 6. 4.]]]]


array([[82., 57., 85.],
       [68., 84., 89.]])

In [58]:
##ue5
import numpy.random as rand

a = rand.uniform(0,1)
mat = rand.uniform(0,1,10)
res = np.argmin(abs(mat-a))
print(a)
print(mat)
print(res)

0.9314241230967545
[0.03569063 0.88027616 0.43795946 0.77610894 0.09082957 0.11583566
 0.49499935 0.02755923 0.60032462 0.75291063]
1


In [84]:
##ue6
import numpy.random as rand
import numpy as np
n = 4
A = np.array([1,2,3,4]).reshape(n,1)
B = np.arange(n)

print(A)
A**B

[[1]
 [2]
 [3]
 [4]]


array([[ 1,  1,  1,  1],
       [ 1,  2,  4,  8],
       [ 1,  3,  9, 27],
       [ 1,  4, 16, 64]])

In [89]:
##ue7
def linearkong(x, a=21, b=7, m=100):
    while True:
        x = (a*x + b) % m
        yield x

def mwc(x, c, a=6, b=100):
    while True:
        aux = a*x + c
        x = aux % b
        c = aux // b
        yield x
        
def corr(nums):
    """
    Calculate the correlation Matrix of the rows of the argument array.

    Parameters
    ----------
    nums: 2d array, shape (n*m)

    Returns
    -------
    array: 2d array, shape (n*n)
      The element at (i,j) is the correlation coefficient between the
      i-th and j-th row of `nums`.
    """
    n = nums.shape[0]
    covm = np.zeros((n, n))
    for i, xi in enumerate(nums):
        for j, xj in enumerate(nums):
            covm[i, j] = ((xi-xi.mean()) * (xj-xj.mean())).mean() / (xi.std() * xj.std())
    return covm

from itertools import islice

N = 5

nums_lin = np.array([list(islice(linearkong(n), 100)) for n in range(N)])
nums_mwc = np.array([list(islice(mwc(n, 30), 100)) for n in range(N)])

corr(nums_lin)


array([[ 1.        ,  0.02850285,  0.09030903,  0.00930093,  0.04950495],
       [ 0.02850285,  1.        ,  0.07650765,  0.04230423,  0.08130813],
       [ 0.09030903,  0.07650765,  1.        ,  0.00450045, -0.00570057],
       [ 0.00930093,  0.04230423,  0.00450045,  1.        ,  0.05250525],
       [ 0.04950495,  0.08130813, -0.00570057,  0.05250525,  1.        ]])