In [1]:
import numpy as np

a = np.array([0, 1, 2, 3])
print(type(a))
a

<class 'numpy.ndarray'>


array([0, 1, 2, 3])

In [2]:
a = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [3]:
a.ndim

2

In [4]:
a.shape

(2, 4)

In [5]:
a = np.array([[1, 2, 3]])
print(a)
print(a.shape)
print(a.ndim)

[[1 2 3]]
(1, 3)
2


In [6]:
a = np.arange(4)
print(type(a))
a

<class 'numpy.ndarray'>


array([0, 1, 2, 3])

In [7]:
np.linspace(-1, 1, 5)

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [8]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [11]:
np.diag(np.array([3, 1, 4, 1]))

array([[3, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 1]])

In [12]:
np.diag(np.array([3, 1, 4, 1]), 1)

array([[0, 3, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

In [13]:
np.diag(np.array([3, 1, 4, 1]), -2)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [3, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 4, 0, 0, 0],
       [0, 0, 0, 1, 0, 0]])

In [14]:
a = np.arange(10)
(a[0], a[4], a[-1])

(0, 4, 9)

In [15]:
a[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [16]:
a[1::2]

array([1, 3, 5, 7, 9])

In [17]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a)
a[1, 0]

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4

In [18]:
a[::2, 1:]

array([[2, 3],
       [8, 9]])

In [19]:
a = np.arange(1, 10)
a[:3] = np.array([-1, -2, -3])
a

array([-1, -2, -3,  4,  5,  6,  7,  8,  9])

In [21]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.stack((a,b))
c

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
d = np.concatenate((a,b))
d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [32]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
c = np.hstack((a,b))
d = np.vstack((a,b))
print(c)
d

[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]
 [ 7  8  9 16 17 18]]


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [35]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
b,c = np.split(a,2)
b,c

(array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]))

In [36]:
a = np.arange(5)
b = a
b[2] = -1
a

array([ 0,  1, -1,  3,  4])

In [37]:
a = np.arange(5)
b = a[::2]
b[2] = -1
a

array([ 0,  1,  2,  3, -1])

In [38]:
a = np.arange(6)
b = a.view()

b.shape = (2, 3)
a[0] = 10

print('a = \n', a)
print('b = \n', b)

a = 
 [10  1  2  3  4  5]
b = 
 [[10  1  2]
 [ 3  4  5]]


In [39]:
def f(x):
    x[2] = -1

a = np.arange(5)
f(a)
a

array([ 0,  1, -1,  3,  4])

In [40]:
a = np.arange(5)
b = a.copy()
b[2] = -1
a

array([0, 1, 2, 3, 4])

In [55]:
a = np.arange(24).reshape((3, 8)).reshape((1,24))
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23]])

In [56]:
np.array([[1, 2], [3, 4]]).ravel()

array([1, 2, 3, 4])

In [58]:
a = np.arange(3)
b = a[None, :]
print(b.shape)
a,b

(1, 3)


(array([0, 1, 2]), array([[0, 1, 2]]))

In [59]:
b = a[:, None]
print(b.shape)
b

(3, 1)


array([[0],
       [1],
       [2]])

In [60]:
np.arange(24).reshape((3, 8)).transpose()

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [61]:
np.arange(24).reshape((3, 8)).T

array([[ 0,  8, 16],
       [ 1,  9, 17],
       [ 2, 10, 18],
       [ 3, 11, 19],
       [ 4, 12, 20],
       [ 5, 13, 21],
       [ 6, 14, 22],
       [ 7, 15, 23]])

In [62]:
a = np.arange(24).reshape((2, 3, 4))
a.transpose().shape

(4, 3, 2)

In [64]:
a = np.arange(24).reshape((2, 3, 4))
a.transpose((0, 2, 1)).shape

(2, 4, 3)

In [66]:
np.sin(np.arange(5))


array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [69]:
[np.sin(t) for t in np.arange(5)]

[0.0,
 0.8414709848078965,
 0.9092974268256817,
 0.1411200080598672,
 -0.7568024953079282]

In [70]:
np.arange(0, 3) + np.arange(10, 13)

array([10, 12, 14])

In [71]:
10 * np.arange(3)

array([ 0, 10, 20])

In [72]:
np.array([0, 1, 2]) == np.array([0, 2, 4])

array([ True, False, False])

In [73]:
np.array_equal(np.array([0, 1, 2]), np.array([0, 1, 3]))

False

In [74]:
a = np.arange(2*3*4).reshape((2, 3, 4))
a.sum()

276

In [82]:
print(a)
a.sum(axis=1)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


array([[12, 15, 18, 21],
       [48, 51, 54, 57]])

In [81]:
a.sum(axis=(1, 2))

array([ 66, 210])

In [83]:
np.array([0, 1, 3, 2]).argmax()

2

In [84]:
x, y = np.ogrid[0:6:1, 0:50:10]
print((x.shape, y.shape))
(x, y)

((6, 1), (1, 5))


(array([[0],
        [1],
        [2],
        [3],
        [4],
        [5]]),
 array([[ 0, 10, 20, 30, 40]]))

In [85]:
x + y

array([[ 0, 10, 20, 30, 40],
       [ 1, 11, 21, 31, 41],
       [ 2, 12, 22, 32, 42],
       [ 3, 13, 23, 33, 43],
       [ 4, 14, 24, 34, 44],
       [ 5, 15, 25, 35, 45]])

In [86]:
np.ogrid[0:13:3j, 0:13:3]

[array([[ 0. ],
        [ 6.5],
        [13. ]]),
 array([[ 0.,  3.,  6.,  9., 12.]])]

In [87]:
x, y = np.ogrid[0:6:1, 0:50:10]
x, y = np.broadcast_arrays(x, y)
print(x)
print(y)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]
 [5 5 5 5 5]]
[[ 0 10 20 30 40]
 [ 0 10 20 30 40]
 [ 0 10 20 30 40]
 [ 0 10 20 30 40]
 [ 0 10 20 30 40]
 [ 0 10 20 30 40]]


In [90]:
x,y = np.meshgrid(np.linspace(0,4,5),np.linspace(0,4,5))
x,y

(array([[0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.],
        [0., 1., 2., 3., 4.]]),
 array([[0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.],
        [2., 2., 2., 2., 2.],
        [3., 3., 3., 3., 3.],
        [4., 4., 4., 4., 4.]]))